name: zeggy_chat
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.15.1
  firebase: ^9.0.3
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  modal_progress_hud: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
